---
stages:
  - test
  - deploy

pkgcheck:
  stage: test
  tags:
    - portage
  image: gentoo/stage3:latest
  before_script:
    - emerge --quiet dev-util/pkgcheck
  script:
    - echo "Revisando ebuilds..."
    - pkgcheck scan
    - echo "No se encontraron problemas en ebuilds."

push_to_master:
  stage: deploy
  tags:
    - docker
  image: alpine:latest
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  before_script:
    - apk add --no-cache git
  script:
    - git remote set-url origin https://CI_ACCESS_TOKEN:$CI_ACCESS_TOKEN@${CI_PROJECT_URL#https://}.git
    - cat .git/config
    - git merge origin/develop
    - ls -ls
    - git push --set-upstream origin master
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
