---
stages:
  - test
  - deploy

pkgcheck:
  stage: test
  tags:
    - portage
  image: gentoo/stage3:latest
  before_script:
    - emerge --quiet dev-util/pkgcheck
  script:
    - echo "Revisando ebuilds..."
    - pkgcheck scan
    - echo "No se encontraron problemas en ebuilds."

push_to_master:
  stage: deploy
  tags:
    - docker
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git status
    #- git checkout master
    #- git merge develop
    #- git push $CI_REPOSITORY_URL
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

