---
stages:
  - test

default:
  image: gentoo/stage3:latest
  before_script:
    - emerge dev-util/pkgcheck

portage:
  stage: test
  tags:
    - portage
  script:
    - echo "Revisando ebuilds..."
    - pkgcheck scan
    - echo "No se encontraron problemas en ebuilds."
