---
stages:
  - test

default:
  image: gentoo/stage3:latest

portage:
  stage: test
  tags:
    - docker
  script:
    - echo "Revisando código..."
    - pkgcheck scan
    - echo "No se encontraron problemas en el código."
